# Generated by Django 4.1.7 on 2023-02-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('yoe', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('passion', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=100)),
            ],
        ),
    ]
